version: '3.8'

services:
  router:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ryohi-router
    ports:
      - "8080:8080"  # Main router port
      - "8081:8081"  # Admin API port
      - "9090:9090"  # Metrics port
    volumes:
      - ./configs:/app/configs:ro
    environment:
      - LOG_LEVEL=info
      - ROUTER_PORT=8080
      - ADMIN_API_KEY=${ADMIN_API_KEY:-your-secret-api-key}
    restart: unless-stopped
    networks:
      - router-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Example backend service 1
  backend1:
    image: nginx:alpine
    container_name: backend1
    networks:
      - router-network
    volumes:
      - ./examples/backend1:/usr/share/nginx/html:ro
    
  # Example backend service 2
  backend2:
    image: nginx:alpine
    container_name: backend2
    networks:
      - router-network
    volumes:
      - ./examples/backend2:/usr/share/nginx/html:ro

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - router-network
    restart: unless-stopped

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./configs/grafana:/etc/grafana/provisioning:ro
    networks:
      - router-network
    restart: unless-stopped
    depends_on:
      - prometheus

networks:
  router-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data: